### PR TITLE
Add list of plugins to readme

### PR DESCRIPTION
**Pull request by TehShrike**
I was confused when I visited the documentation and couldn't find any detailed documentation on what this plugin does.

Providing a list of plugin libraries in the readme gives people some direction on how to go find details without them having to read the source code.

### CODE REVIEW

**Comment by lkraav** [comment]
Hmm, the list of plugins used to be there before the last major version update. I wonder if the omission now is accidental or on purpose?

**Comment by jonathantneal** [comment]
@lkraav, the omission was because I couldn’t figure out how to update the list based on the evergreen browserslist status in PostCSS Preset Env. However, this list keeps it simple and I like that.

**Comment by jonathantneal** [comment]
Thanks @TehShrike 😄

**Comment by TehShrike** [comment]
👍

**Pull request merged**
