### PR TITLE
Update postcss-partial-import dependency

### PR DESCRIPTION
**Pull request by jboelen**
A new version of `postcss-partial-import` was released and adds new and useful features. This change updates the `package.json` to use this newer version.

### CODE REVIEW

**Comment by jboelen** [comment]
Looks like the tests are broken re: https://github.com/jonathantneal/precss/pull/79

**Comment by CookPete** [comment]
This can be bumped to `2.1.0` now 👍

**Comment by adelsz** [comment]
Yes, the `postcss-partial-import` dep. is terribly outdated.
Is a merge coming anytime soon?

**Comment by karimsa** [comment]
This dependency is even more outdated now and is causing builds to break: jonathantneal/postcss-partial-import#41

**Comment by oshalygin** [comment]
Any chance we can merge this or fork and use the new dependency?

**Pull request merged**
