### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by jonathantneal**
The gist of this PR is that all features are consolidated into postcss-advanced-variables and postcss-preset-env.

**PostCSS Advanced Variables** handle most of the Sass-like syntax, including variables, iterables, and conditionals. **PostCSS Extend Rule** handles extends like Sass, but preserves source ordering more as the typical developer might expect. **PostCSS Mixin** handles Sass like nesting, while **PostCSS At Root** handles Sass like rooting. **PostCSS Property Lookup** sticks around, as it was popular syntactical sugar in the last version.

This resolves countless bugs, offloads plugin ordering to a few other plugins, and generally restores order to the galaxy.

### CODE REVIEW

**Comment by lkraav** [comment]
@jonathantneal isn't `precss` already at 2.0.0 from 6 mo ago? Are we looking at 3.0.0 here?

**Comment by jonathantneal** [comment]
@ikraav, you are correct.

**Comment by raulferras** [comment]
Maybe I did not understand properly your description, but I see you removed `postcss-mixins` from package.json. Is that correct?

**Comment by raulferras** [comment]
Oh ok, I see postcss-advanced-variables already covers that.

**Pull request merged**
